# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuGvbmmnjbhdTLW44oJkrHm_9GE0UENI
"""

num = int(input("Enter your num : "))
if(num%2==0):
  print(num,"is an even num.")
else:
  print(num,("is an odd num."))